import * as THREE from '../vendor/three.module.js';
import {buildModel} from '../model.js';
import {buildTank} from '../tank/model.js';
import {getLevel} from './levels.js';
const $=id=>document.getElementById(id),level=getLevel('trial-01');
const scene=new THREE.Scene();scene.background=new THREE.Color(level.palette.sky);scene.fog=new THREE.Fog(level.palette.sky,22,48);
const host=$('scene'),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-10,10,8,-8,.1,80);camera.position.set(0,2,28);camera.lookAt(0,2,0);scene.add(new THREE.HemisphereLight(0xfffdf4,0x7a9081,2.6));const sun=new THREE.DirectionalLight(0xffe2a5,2.3);sun.position.set(-8,16,14);sun.castShadow=true;scene.add(sun);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.7,...extra});const mats={floor:mat('#cbd9cf'),line:mat('#a9bbaa'),gold:mat('#efb63b',{emissive:'#875c00',emissiveIntensity:.2}),red:mat('#d66f5d',{emissive:'#6f1f18',emissiveIntensity:.3}),dark:mat('#39473c')};
function mesh(geo,material,parent=scene){const o=new THREE.Mesh(geo,material);o.castShadow=o.receiveShadow=true;parent.add(o);return o}function box(w,h,d,material,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),material,parent)}
// 源模型的 Y 轴是车顶方向、X 轴是车头方向。先把车顶转向镜头，
// 再将车头转到屏幕上方；战场始终是屏幕的 X/Y 平面。
function topDownRig(template,scale,heading=Math.PI/2){const rig=new THREE.Group(),visual=template.clone(true);visual.rotation.x=Math.PI/2;rig.rotation.z=heading;rig.scale.setScalar(scale);rig.add(visual);return rig}
const floor=box(26,.35,10,mats.floor);floor.position.y=-7.8;for(let x=-12;x<=12;x+=2){const stripe=box(.05,.03,10,mats.line);stripe.position.set(x,-7.6,0)}for(let y=-6;y<=12;y+=3){const stripe=box(26,.03,.05,mats.line);stripe.position.set(0,y,-.02)}
// 玩家坦克：车顶朝向镜头，炮管/车头指向屏幕上方。
const tankRig=buildTank(),player=new THREE.Group();tankRig.tank.rotation.x=Math.PI/2;player.rotation.z=Math.PI/2;player.add(tankRig.tank);tankRig.tank.scale.setScalar(.42);player.position.set(0,-3,0);scene.add(player);const tankGlow=mesh(new THREE.TorusGeometry(.98,.05,8,32),new THREE.MeshBasicMaterial({color:'#f1c448',transparent:true,opacity:.75}),player);tankGlow.position.z=.35;
// 上方单位是完整合体。分离时隐藏车体、保留翼龙，并生成独立落下的战车。
const enemyRig=buildModel();enemyRig.poseCreature({stand:0,wing:.42});const combinedTemplate=enemyRig.model,carrierTemplate=enemyRig.chassis.clone(true);
const enemies=[],droppedCars=[],shots=[],enemyShots=[],sparks=[];const enemyLayer=new THREE.Group();scene.add(enemyLayer);const bulletGeo=new THREE.SphereGeometry(.14,10,8),enemyBulletGeo=new THREE.SphereGeometry(.18,10,8);
let state='ready',time=0,last=performance.now(),playerX=0,move=0,fireHeld=false,fireClock=0,waveIndex=0,score=0,lives=level.player.lives,messageUntil=0,deployClock=0;
function say(text,seconds=2.3){$('message').textContent=text;messageUntil=time+seconds}
function burst(pos,color='#efb63b',count=12){for(let i=0;i<count;i++){const s=mesh(new THREE.SphereGeometry(.055,6,5),new THREE.MeshBasicMaterial({color,transparent:true}));s.position.copy(pos);s.userData={v:new THREE.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7,Math.random()-.5),life:.45};sparks.push(s)}}
function spawnWave(index){enemyLayer.clear();enemies.length=0;droppedCars.splice(0).forEach(o=>o.removeFromParent());const wave=level.waves[index];const spacing=4.1;for(let i=0;i<wave.count;i++){const combined=topDownRig(combinedTemplate,.32);combined.position.set((i-(wave.count-1)/2)*spacing,6.6+(i%2)*.65,0);combined.userData={homeX:combined.position.x,homeY:combined.position.y,health:wave.health,phase:'combined',phaseTime:0,hit:0};enemyLayer.add(combined);enemies.push(combined)}waveIndex=index;deployClock=wave.deployEvery;say(`${wave.label} · 留意投放与俯冲`);sync()}
function shoot(){if(state!=='playing')return;const b=mesh(bulletGeo,mats.gold);b.position.set(playerX,player.position.y+.82,.3);b.userData={v:17};shots.push(b)}
function enemyShoot(x,y){const b=mesh(enemyBulletGeo,mats.red);b.position.set(x,y,.1);b.userData={v:-8};enemyShots.push(b)}
function damage(text='坦克受击！'){lives--;burst(player.position,'#d66f5d',18);say(lives?text:'试玩结束',2);if(lives<=0)end('坦克已损坏','再试一次：先横移躲过投放战车，再处理掉头俯冲的翼龙。','重新开始');sync()}
function end(title,copy,label){state=title==='试玩完成'?'won':'lost';$('overlay').hidden=false;$('overlay').querySelector('.eyebrow').textContent=state==='won'?'试玩关卡 · 完成':'试玩关卡 · 失败';$('overlay').querySelector('h2').textContent=title;$('overlay').querySelector('p:not(.eyebrow)').textContent=copy;$('start').textContent=label}
function advance(){if(waveIndex<level.waves.length-1)spawnWave(waveIndex+1);else end('试玩完成','你击退了合体巡航、战车投放和翼龙俯冲。下一步可以直接在关卡配置中增加合体数量、投放频率与俯冲速度。','再玩一次')}
function reset(){enemyLayer.clear();enemies.length=0;[...shots,...enemyShots,...sparks].forEach(o=>o.removeFromParent());shots.length=enemyShots.length=sparks.length=0;droppedCars.splice(0).forEach(o=>o.removeFromParent());time=0;playerX=0;move=0;fireHeld=false;fireClock=0;waveIndex=0;score=0;lives=level.player.lives;state='playing';$('overlay').hidden=true;spawnWave(0);say('坦克自动开火 · 左右躲避投放',3)}
function sync(){ $('score').textContent=String(score).padStart(6,'0');$('lives').textContent=Array.from({length:level.player.lives},(_,i)=>i<lives?'●':'○').join(' ');$('wave-label').textContent='波次 '+String(waveIndex+1).padStart(2,'0');$('objective').textContent=`残余合体 ${enemies.filter(e=>e.parent).length}`;}
function resize(){const w=host.clientWidth,h=host.clientHeight,aspect=w/h,viewH=18;renderer.setSize(w,h,false);camera.left=-viewH*aspect/2;camera.right=viewH*aspect/2;camera.top=viewH/2;camera.bottom=-viewH/2;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
function hit(a,b,r){return a.position.distanceTo(b.position)<r}
function deploy(enemy,wave){const d=enemy.userData;if(d.phase!=='combined')return;d.phase='turn';d.phaseTime=0;const car=topDownRig(carrierTemplate,.32);car.position.copy(enemy.position);car.position.y-=.7;car.userData={v:4.3,health:1};scene.add(car);droppedCars.push(car);const chassis=enemy.getObjectByName('Four-wheel carrier');if(chassis)chassis.visible=false;say('战车已投放！翼龙正在掉头。',2)}
function update(dt){if(state!=='playing')return;time+=dt;playerX=THREE.MathUtils.clamp(playerX+move*level.player.speed*dt,-8.2,8.2);player.position.x=playerX;tankGlow.material.opacity=.46+Math.sin(time*5)*.24;
 fireClock-=dt;if((fireHeld||true)&&fireClock<=0){shoot();fireClock=level.player.fireRate}
 const wave=level.waves[waveIndex];deployClock-=dt;if(deployClock<=0){const target=enemies.find(e=>e.parent&&e.userData.phase==='combined');if(target)deploy(target,wave);deployClock=wave.deployEvery;}
 enemies.forEach((e,i)=>{if(!e.parent)return;const d=e.userData;const drift=Math.sin(time*1.2+i*.7)*wave.drift;if(d.phase==='combined'){e.position.x=d.homeX+drift;e.position.y=d.homeY+Math.sin(time*2+i)*.14;e.rotation.z=Math.PI/2+Math.sin(time*4+i)*.035;}else if(d.phase==='turn'){d.phaseTime+=dt;e.rotation.z=THREE.MathUtils.lerp(Math.PI/2,-Math.PI/2,Math.min(1,d.phaseTime/.55));if(d.phaseTime>=.55){d.phase='dive';d.target=playerX;}}else{e.position.x=THREE.MathUtils.lerp(e.position.x,d.target,dt*1.35);e.position.y-=wave.diveSpeed*dt;e.rotation.z=-Math.PI/2+Math.sin(time*8+i)*.08;if(e.position.y<player.position.y+.55){const connects=Math.abs(e.position.x-playerX)<1.15;e.removeFromParent();if(connects){damage('翼龙俯冲命中坦克！');burst(e.position,'#d66f5d',20)}else burst(e.position,'#a9bbaa',8);}}const wings=e.getObjectByName('Left small triangular wing');if(wings)wings.rotation.x=Math.sin(time*11+i)*.35;});
 droppedCars.forEach((car,i)=>{car.position.y-=car.userData.v*dt;if(car.position.y<player.position.y-.25){const connects=Math.abs(car.position.x-playerX)<1.1;car.removeFromParent();droppedCars.splice(i,1);if(connects)damage('投放战车撞击坦克！');else burst(car.position,'#a9bbaa',8);}});
 shots.forEach((b,i)=>{b.position.y+=b.userData.v*dt;b.rotation.y+=dt*9;if(b.position.y>12){b.removeFromParent();shots.splice(i,1);return}for(const car of droppedCars){if(car.parent&&hit(b,car,.9)){car.removeFromParent();droppedCars.splice(droppedCars.indexOf(car),1);score+=80;burst(car.position);b.removeFromParent();shots.splice(i,1);return}}for(const e of enemies){if(e.parent&&hit(b,e,.92)){e.userData.health--;burst(b.position);b.removeFromParent();shots.splice(i,1);if(e.userData.health<=0){e.removeFromParent();score+=wave.score;burst(e.position, '#f1c448',18)}break}}});
 enemyShots.forEach((b,i)=>{b.position.y+=b.userData.v*dt;if(b.position.y<-7){b.removeFromParent();enemyShots.splice(i,1);return}if(Math.abs(b.position.x-playerX)<1.15&&b.position.y<-4){b.removeFromParent();enemyShots.splice(i,1);damage();}});sparks.forEach((s,i)=>{s.position.addScaledVector(s.userData.v,dt);s.userData.life-=dt;s.material.opacity=Math.max(0,s.userData.life*2);if(s.userData.life<=0){s.removeFromParent();sparks.splice(i,1)}});if(enemies.length&&enemies.every(e=>!e.parent)&&!droppedCars.length)advance();if(time>messageUntil)$('message').textContent='左右移动坦克，自动发射能量弹。';sync()}
$('start').onclick=()=>{if(state==='ready'||state==='won'||state==='lost')reset()};$('restart').onclick=reset;window.addEventListener('keydown',e=>{if(['ArrowLeft','KeyA'].includes(e.code)){move=-1;e.preventDefault()}if(['ArrowRight','KeyD'].includes(e.code)){move=1;e.preventDefault()}if(e.code==='Space'){fireHeld=true;e.preventDefault()}});window.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA','ArrowRight','KeyD'].includes(e.code))move=0;if(e.code==='Space')fireHeld=false});
for(const b of document.querySelectorAll('[data-move]')){const dir=Number(b.dataset.move);b.addEventListener('pointerdown',e=>{e.preventDefault();move=dir;b.setPointerCapture?.(e.pointerId)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>move=0)}const fire=$('fire');fire.addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true});for(const ev of ['pointerup','pointercancel','lostpointercapture'])fire.addEventListener(ev,()=>fireHeld=false);
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);sync();
