import * as THREE from '../vendor/three.module.js';
import {buildModel} from '../model.js';
import {buildTank} from '../tank/model.js';
import {getLevel} from './levels.js';
const $=id=>document.getElementById(id),level=getLevel('trial-01');
const scene=new THREE.Scene();scene.background=new THREE.Color(level.palette.sky);scene.fog=new THREE.Fog(level.palette.sky,22,48);
const host=$('scene'),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;host.append(renderer.domElement);
const camera=new THREE.OrthographicCamera(-10,10,8,-8,.1,80);camera.position.set(0,2,28);camera.lookAt(0,2,0);scene.add(new THREE.HemisphereLight(0xfffdf4,0x7a9081,2.6));const sun=new THREE.DirectionalLight(0xffe2a5,2.3);sun.position.set(-8,16,14);sun.castShadow=true;scene.add(sun);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.7,...extra});const mats={floor:mat('#cbd9cf'),line:mat('#a9bbaa'),gold:mat('#efb63b',{emissive:'#875c00',emissiveIntensity:.2}),red:mat('#d66f5d',{emissive:'#6f1f18',emissiveIntensity:.3}),dark:mat('#39473c'),white:mat('#fffdf5')};
function mesh(geo,material,parent=scene){const o=new THREE.Mesh(geo,material);o.castShadow=o.receiveShadow=true;parent.add(o);return o}function box(w,h,d,material,parent=scene){return mesh(new THREE.BoxGeometry(w,h,d),material,parent)}
const floor=box(26,.35,10,mats.floor);floor.position.y=-7.8;for(let x=-12;x<=12;x+=2){const stripe=box(.05,.03,10,mats.line);stripe.position.set(x,-7.6,0)}for(let y=-6;y<=12;y+=3){const stripe=box(26,.03,.05,mats.line);stripe.position.set(0,y,-.02)}
const rig=buildModel();rig.poseCreature({stand:0,wing:.62});const player=new THREE.Group();player.add(rig.chassis);rig.chassis.scale.setScalar(.62);player.position.set(0,-2.5,0);scene.add(player);const wheels=rig.chassis.children.filter(o=>o.name==='Wheel with tread and spoked rim');
const glow=mesh(new THREE.TorusGeometry(1.65,.05,8,32),new THREE.MeshBasicMaterial({color:'#f1c448',transparent:true,opacity:.8}),player);glow.rotation.x=Math.PI/2;glow.position.y=.1;
const creatureTemplate=rig.creature.clone(true);const enemies=[],shots=[],enemyShots=[],sparks=[];const enemyLayer=new THREE.Group();scene.add(enemyLayer);const bulletGeo=new THREE.SphereGeometry(.14,10,8),enemyBulletGeo=new THREE.SphereGeometry(.18,10,8);
const enemyMat=new THREE.MeshStandardMaterial({color:'#f5b800',roughness:.32,metalness:.04});
let boss=null,bossHp=0,state='ready',time=0,last=performance.now(),playerX=0,move=0,fireHeld=false,fireClock=0,waveIndex=0,score=0,lives=level.player.lives,messageUntil=0,diveClock=0,bossShot=0;
function say(text,seconds=2.3){$('message').textContent=text;messageUntil=time+seconds}
function disposeGroup(group){group.traverse(o=>{if(o.isMesh){o.geometry?.dispose?.();}});group.removeFromParent()}
function spawnWave(index){enemyLayer.clear();enemies.length=0;const wave=level.waves[index];const spacing=3.15;for(let row=0;row<wave.rows;row++)for(let col=0;col<wave.cols;col++){const enemy=creatureTemplate.clone(true);enemy.scale.setScalar(.43);enemy.rotation.y=Math.PI/2;enemy.position.set((col-(wave.cols-1)/2)*spacing,5.6+row*1.8,0);enemy.userData={homeX:enemy.position.x,homeY:enemy.position.y,health:wave.health,dive:0,hit:0};enemyLayer.add(enemy);enemies.push(enemy)}waveIndex=index;diveClock=wave.diveEvery;say(`${wave.label} · 清除全部翼龙`);sync()}
function makeBoss(){const built=buildTank();boss=built.tank;boss.scale.setScalar(.74);boss.position.set(0,6.8,0);boss.rotation.y=.04;scene.add(boss);bossHp=level.boss.health;boss.userData.barrels=built.barrelParts;say('双炮坦克出现！',3);sync()}
function burst(pos,color='#efb63b',count=12){for(let i=0;i<count;i++){const s=mesh(new THREE.SphereGeometry(.055,6,5),new THREE.MeshBasicMaterial({color,transparent:true}));s.position.copy(pos);s.userData={v:new THREE.Vector3((Math.random()-.5)*7,(Math.random()-.5)*7,Math.random()-.5),life:.45};sparks.push(s)}}
function shoot(){if(state!=='playing')return;const b=mesh(bulletGeo,mats.gold);b.position.set(playerX,-2.4,.3);b.userData={v:17};shots.push(b)}
function enemyShoot(x,y){const b=mesh(enemyBulletGeo,mats.red);b.position.set(x,y,.1);b.userData={v:-8};enemyShots.push(b)}
function damage(){lives--;burst(player.position,'#d66f5d',18);say(lives?'战车受击！继续躲避。':'试玩结束',2);if(lives<=0){state='lost';end('战车已损坏','再试一次，观察翼龙俯冲轨迹后提前横移。','重新开始')}sync()}
function end(title,copy,label){state=title==='试玩完成'?'won':'lost';$('overlay').hidden=false;$('overlay').querySelector('.eyebrow').textContent=state==='won'?'试玩关卡 · 完成':'试玩关卡 · 失败';$('overlay').querySelector('h2').textContent=title;$('overlay').querySelector('p:not(.eyebrow)').textContent=copy;$('start').textContent=label}
function advance(){if(waveIndex<level.waves.length-1)spawnWave(waveIndex+1);else makeBoss()}
function reset(){enemyLayer.clear();enemies.length=0;shots.splice(0).forEach(o=>o.removeFromParent());enemyShots.splice(0).forEach(o=>o.removeFromParent());sparks.splice(0).forEach(o=>o.removeFromParent());boss?.removeFromParent();boss=null;time=0;playerX=0;move=0;fireHeld=false;fireClock=0;waveIndex=0;score=0;lives=level.player.lives;bossHp=0;state='playing';$('overlay').hidden=true;spawnWave(0);say('自动火力已启动 · 左右躲避',3)}
function sync(){ $('score').textContent=String(score).padStart(6,'0');$('lives').textContent=Array.from({length:level.player.lives},(_,i)=>i<lives?'●':'○').join(' ');$('wave-label').textContent=boss?'首领战':'波次 '+String(waveIndex+1).padStart(2,'0');$('objective').textContent=boss?`坦克装甲 ${Math.max(0,bossHp)} / ${level.boss.health}`:`剩余翼龙 ${enemies.filter(e=>e.parent).length}`;}
function resize(){const w=host.clientWidth,h=host.clientHeight,aspect=w/h,viewH=18;renderer.setSize(w,h,false);camera.left=-viewH*aspect/2;camera.right=viewH*aspect/2;camera.top=viewH/2;camera.bottom=-viewH/2;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();
function hit(a,b,r){return a.position.distanceTo(b.position)<r}
function update(dt){if(state!=='playing')return;time+=dt;playerX=THREE.MathUtils.clamp(playerX+move*level.player.speed*dt,-8.5,8.5);player.position.x=playerX;wheels.forEach(w=>w.rotation.z-=move*dt*5);glow.material.opacity=.5+Math.sin(time*5)*.24;
 fireClock-=dt;if((fireHeld||true)&&fireClock<=0){shoot();fireClock=level.player.fireRate}
 const wave=level.waves[waveIndex];if(!boss){diveClock-=dt;if(diveClock<=0){const active=enemies.filter(e=>e.parent&&!e.userData.dive);if(active.length){const e=active[Math.floor(Math.random()*active.length)];e.userData.dive=1;e.userData.target=playerX;}diveClock=wave.diveEvery;}
  enemies.forEach((e,i)=>{if(!e.parent)return;const d=e.userData;const drift=Math.sin(time*1.2+i*.7)*wave.drift;if(d.dive){d.dive+=dt;e.position.x=THREE.MathUtils.lerp(d.homeX+drift,d.target,d.dive*.22);e.position.y=d.homeY-d.dive*7.4;e.rotation.z=Math.sin(d.dive*6)*.35;if(e.position.y<-7){d.dive=0;e.position.set(d.homeX,d.homeY,0);e.rotation.z=0;enemyShoot(e.position.x,-1)}}else{e.position.x=d.homeX+drift;e.position.y=d.homeY+Math.sin(time*2+i)*.14;e.rotation.z=Math.sin(time*5+i)*.08;}e.rotation.y=Math.PI/2;const wings=e.children.filter(o=>o.name?.includes('wing'));wings.forEach((w,j)=>w.rotation.x=(j?1:-1)*Math.sin(time*10+i)*.25);});
 }else{boss.position.x=Math.sin(time*.75)*5.7;boss.position.y=6.8+Math.sin(time*1.3)*.25;boss.rotation.y=Math.sin(time*.8)*.08;boss.userData.barrels.forEach((b,i)=>b.rotation.z=.12+Math.sin(time*2+i)*.08);bossShot-=dt;if(bossShot<=0){enemyShoot(boss.position.x-1,5.5);enemyShoot(boss.position.x+1,5.5);bossShot=level.boss.shotEvery;}}
 shots.forEach((b,i)=>{b.position.y+=b.userData.v*dt;b.rotation.y+=dt*9;if(b.position.y>12){b.removeFromParent();shots.splice(i,1);return}if(boss&&hit(b,boss,2.1)){bossHp--;score+=50;burst(b.position);b.removeFromParent();shots.splice(i,1);if(bossHp<=0){burst(boss.position,'#f1c448',35);boss.removeFromParent();boss=null;score+=level.boss.score;end('试玩完成','你完成了三波翼龙编队与双炮坦克首领战。下一步可以直接在关卡配置中增加波次、俯冲频率和坦克血量。','再玩一次');}return}for(const e of enemies){if(e.parent&&hit(b,e,.78)){e.removeFromParent();score+=wave.score;burst(e.position);b.removeFromParent();shots.splice(i,1);break}}});
 enemyShots.forEach((b,i)=>{b.position.y+=b.userData.v*dt;if(b.position.y<-8){b.removeFromParent();enemyShots.splice(i,1);return}if(Math.abs(b.position.x-playerX)<1.15&&b.position.y<-2.2){b.removeFromParent();enemyShots.splice(i,1);damage();}});sparks.forEach((s,i)=>{s.position.addScaledVector(s.userData.v,dt);s.userData.life-=dt;s.material.opacity=Math.max(0,s.userData.life*2);if(s.userData.life<=0){s.removeFromParent();sparks.splice(i,1)}});if(!boss&&enemies.length&&enemies.every(e=>!e.parent))advance();if(time>messageUntil)$('message').textContent='左右移动战车，自动发射能量弹。';sync()}
$('start').onclick=()=>{if(state==='ready'||state==='won'||state==='lost')reset()};$('restart').onclick=reset;window.addEventListener('keydown',e=>{if(['ArrowLeft','KeyA'].includes(e.code)){move=-1;e.preventDefault()}if(['ArrowRight','KeyD'].includes(e.code)){move=1;e.preventDefault()}if(e.code==='Space'){fireHeld=true;e.preventDefault()}});window.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA','ArrowRight','KeyD'].includes(e.code))move=0;if(e.code==='Space')fireHeld=false});
for(const b of document.querySelectorAll('[data-move]')){const dir=Number(b.dataset.move);const start=e=>{e.preventDefault();move=dir;b.setPointerCapture?.(e.pointerId)};b.addEventListener('pointerdown',start);for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>move=0)}const fire=$('fire');fire.addEventListener('pointerdown',e=>{e.preventDefault();fireHeld=true});for(const ev of ['pointerup','pointercancel','lostpointercapture'])fire.addEventListener(ev,()=>fireHeld=false);
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);sync();
