// 关卡只在这里配：渲染和碰撞代码不包含关卡数值。
// 新增关卡前，请阅读 docs/LEVEL_DESIGN.md；每一关保持 3 波，并只引入一个新的主压力。
const basePlayer=Object.freeze({lives:4,fireRate:.43,speed:12});
const palette=Object.freeze({sky:'#dfe9e4',fog:'#dfe9e4',accent:'#efb63b'});
const wave=(label,overrides={})=>({
  label,count:4,formation:'line',health:2,drift:1.5,driftPattern:'sway',
  firstDeployAfter:5.8,deployEvery:3.6,deployPattern:'single',diveSpeed:6.4,
  firstProjectileAfter:5.6,projectileEvery:4.8,powerDrops:[],score:240,...overrides
});
const level=(number,name,waves,chapter)=>({
  id:`level-${String(number).padStart(2,'0')}`,name,chapter,palette,player:{...basePlayer},waves
});

export const LEVELS=[
 level(1,'首次拦截',[
  wave('合体侦察队',{count:3,formation:'line',drift:1.15,driftPattern:'still',firstDeployAfter:99,firstProjectileAfter:99,score:180}),
  wave('分离投放队',{count:4,formation:'wedge',drift:1.35,firstDeployAfter:7.2,deployEvery:5.0,firstProjectileAfter:99,powerDrops:[{afterDefeat:2,type:'double',landing:'safe'}],score:220}),
  wave('翼龙突袭队',{count:4,formation:'grid',drift:1.6,firstDeployAfter:5.4,deployEvery:4.25,firstProjectileAfter:99,diveSpeed:6.7,score:270})
 ],'识别'),
 level(2,'编队缺口',[
  wave('双列巡航队',{count:4,formation:'line',drift:1.35,firstDeployAfter:99,firstProjectileAfter:7.2,projectileEvery:5.8,score:220}),
  wave('错位投放队',{count:4,formation:'stagger',drift:1.65,firstDeployAfter:6.2,deployEvery:4.5,firstProjectileAfter:6.0,projectileEvery:5.5,diveSpeed:6.8,score:270}),
  wave('缺口追击队',{count:5,formation:'grid',drift:1.8,firstDeployAfter:5.1,deployEvery:4.05,firstProjectileAfter:5.4,projectileEvery:5.1,diveSpeed:7.0,score:320})
 ],'识别'),
 level(3,'交错巡航',[
  wave('交错侦察队',{count:4,formation:'stagger',drift:1.55,firstDeployAfter:99,firstProjectileAfter:6.8,projectileEvery:5.5,score:250}),
  wave('斜列投放队',{count:5,formation:'wedge',drift:1.85,firstDeployAfter:5.8,deployEvery:4.15,firstProjectileAfter:5.4,projectileEvery:5.0,powerDrops:[{afterDefeat:3,type:'spread',landing:'safe'}],score:310}),
  wave('交错追击队',{count:5,formation:'grid',drift:2.05,firstDeployAfter:4.75,deployEvery:3.8,firstProjectileAfter:4.9,projectileEvery:4.7,diveSpeed:7.2,score:370})
 ],'识别'),
 level(4,'落点预警',[
  wave('回旋侦察队',{count:5,formation:'stagger',drift:1.8,driftPattern:'sweep',firstDeployAfter:99,firstProjectileAfter:6.3,projectileEvery:5.1,score:280}),
  wave('落点投放队',{count:5,formation:'grid',drift:2.1,driftPattern:'sweep',firstDeployAfter:5.5,deployEvery:3.95,firstProjectileAfter:5.0,projectileEvery:4.65,diveSpeed:7.1,score:340}),
  wave('预警突袭队',{count:5,formation:'wedge',drift:2.25,driftPattern:'sweep',firstDeployAfter:4.5,deployEvery:3.6,firstProjectileAfter:4.5,projectileEvery:4.4,diveSpeed:7.35,powerDrops:[{afterDefeat:3,type:'shield',landing:'safe'}],score:410})
 ],'识别'),
 level(5,'基础考验',[
  wave('扩散巡航队',{count:5,formation:'wedge',drift:2.0,firstDeployAfter:6.1,deployEvery:4.15,firstProjectileAfter:5.5,projectileEvery:4.9,score:320}),
  wave('边界投放队',{count:6,formation:'stagger',drift:2.3,firstDeployAfter:5.0,deployEvery:3.65,firstProjectileAfter:4.8,projectileEvery:4.45,diveSpeed:7.35,score:390}),
  wave('基础突袭队',{count:6,formation:'grid',drift:2.45,firstDeployAfter:4.2,deployEvery:3.35,firstProjectileAfter:4.35,projectileEvery:4.15,diveSpeed:7.6,score:460})
 ],'识别'),
 level(6,'炮火校准',[
  wave('炮火侦察队',{count:5,formation:'line',drift:2.05,firstDeployAfter:99,firstProjectileAfter:5.4,projectileEvery:4.45,score:360}),
  wave('炮火投放队',{count:6,formation:'grid',drift:2.35,firstDeployAfter:5.25,deployEvery:3.75,firstProjectileAfter:4.5,projectileEvery:3.95,powerDrops:[{afterDefeat:3,type:'rapid',landing:'safe'}],score:430}),
  wave('炮火突袭队',{count:6,formation:'stagger',drift:2.55,firstDeployAfter:4.35,deployEvery:3.3,firstProjectileAfter:3.9,projectileEvery:3.7,diveSpeed:7.75,score:500})
 ],'预判'),
 level(7,'低空预判',[
  wave('低空巡航队',{count:6,formation:'grid',drift:2.2,firstDeployAfter:5.8,deployEvery:3.85,firstProjectileAfter:4.8,projectileEvery:4.0,score:390}),
  wave('低空投放队',{count:6,formation:'wedge',drift:2.55,firstDeployAfter:4.75,deployEvery:3.4,firstProjectileAfter:4.05,projectileEvery:3.65,diveSpeed:7.85,score:470}),
  wave('低空追击队',{count:7,formation:'stagger',drift:2.7,firstDeployAfter:3.95,deployEvery:3.0,firstProjectileAfter:3.6,projectileEvery:3.4,diveSpeed:8.05,powerDrops:[{afterDefeat:4,type:'slow',landing:'safe'}],score:550})
 ],'预判'),
 level(8,'双线接近',[
  wave('双线侦察队',{count:6,formation:'line',drift:2.3,firstDeployAfter:5.6,deployEvery:3.75,firstProjectileAfter:4.65,projectileEvery:3.9,powerDrops:[{afterDefeat:3,type:'double',landing:'gap'}],score:420}),
  wave('双线投放队',{count:7,formation:'grid',drift:2.65,deployPattern:'alternate',firstDeployAfter:4.55,deployEvery:3.25,firstProjectileAfter:3.95,projectileEvery:3.5,diveSpeed:8.0,score:500}),
  wave('双线突袭队',{count:7,formation:'wedge',drift:2.85,deployPattern:'alternate',firstDeployAfter:3.8,deployEvery:2.9,firstProjectileAfter:3.45,projectileEvery:3.2,diveSpeed:8.2,powerDrops:[{afterDefeat:4,type:'shield',landing:'safe'}],score:590})
 ],'预判'),
 level(9,'静默压力',[
  wave('静默巡航队',{count:6,formation:'wedge',drift:2.45,firstDeployAfter:99,firstProjectileAfter:4.25,projectileEvery:3.7,score:450}),
  wave('静默投放队',{count:7,formation:'stagger',drift:2.75,firstDeployAfter:4.7,deployEvery:3.2,firstProjectileAfter:3.8,projectileEvery:3.35,diveSpeed:8.1,score:530}),
  wave('静默追击队',{count:7,formation:'grid',drift:2.95,firstDeployAfter:3.75,deployEvery:2.85,firstProjectileAfter:3.3,projectileEvery:3.05,diveSpeed:8.3,score:620})
 ],'预判'),
 level(10,'编队转场',[
  wave('转场侦察队',{count:7,formation:'stagger',drift:2.6,driftPattern:'sweep',firstDeployAfter:5.4,deployEvery:3.45,firstProjectileAfter:4.2,projectileEvery:3.55,score:480}),
  wave('转场投放队',{count:7,formation:'wedge',drift:2.9,driftPattern:'sweep',deployPattern:'alternate',firstDeployAfter:4.35,deployEvery:3.0,firstProjectileAfter:3.55,projectileEvery:3.15,diveSpeed:8.25,powerDrops:[{afterDefeat:4,type:'spread',landing:'safe'}],score:570}),
  wave('转场突袭队',{count:8,formation:'grid',drift:3.1,driftPattern:'sweep',deployPattern:'alternate',firstDeployAfter:3.55,deployEvery:2.65,firstProjectileAfter:3.05,projectileEvery:2.9,diveSpeed:8.45,score:670})
 ],'预判'),
 level(11,'火力选择',[
  wave('火力侦察队',{count:7,formation:'line',drift:2.75,firstDeployAfter:5.1,deployEvery:3.3,firstProjectileAfter:3.95,projectileEvery:3.35,score:520}),
  wave('火力投放队',{count:8,formation:'grid',drift:3.05,deployPattern:'alternate',firstDeployAfter:4.15,deployEvery:2.85,firstProjectileAfter:3.35,projectileEvery:2.95,powerDrops:[{afterDefeat:4,type:'rapid',landing:'gap'}],score:620}),
  wave('火力突袭队',{count:8,formation:'stagger',drift:3.25,deployPattern:'alternate',firstDeployAfter:3.35,deployEvery:2.55,firstProjectileAfter:2.85,projectileEvery:2.7,diveSpeed:8.55,score:720})
 ],'选择'),
 level(12,'无援穿行',[
  wave('无援巡航队',{count:7,formation:'wedge',drift:2.85,firstDeployAfter:4.9,deployEvery:3.15,firstProjectileAfter:3.8,projectileEvery:3.15,score:550}),
  wave('无援投放队',{count:8,formation:'stagger',drift:3.15,deployPattern:'alternate',firstDeployAfter:3.95,deployEvery:2.75,firstProjectileAfter:3.1,projectileEvery:2.75,diveSpeed:8.5,score:650}),
  wave('无援突袭队',{count:8,formation:'grid',drift:3.35,deployPattern:'alternate',firstDeployAfter:3.15,deployEvery:2.45,firstProjectileAfter:2.65,projectileEvery:2.55,diveSpeed:8.7,score:760})
 ],'选择'),
 level(13,'护盾窗口',[
  wave('护盾侦察队',{count:8,formation:'grid',drift:2.95,firstDeployAfter:4.85,deployEvery:3.05,firstProjectileAfter:3.65,projectileEvery:3.0,score:590}),
  wave('护盾投放队',{count:8,formation:'wedge',drift:3.3,deployPattern:'alternate',firstDeployAfter:3.8,deployEvery:2.65,firstProjectileAfter:2.95,projectileEvery:2.6,diveSpeed:8.65,powerDrops:[{afterDefeat:4,type:'shield',landing:'safe'}],score:690}),
  wave('护盾突袭队',{count:9,formation:'stagger',health:3,drift:3.45,deployPattern:'alternate',firstDeployAfter:3.05,deployEvery:2.35,firstProjectileAfter:2.5,projectileEvery:2.4,diveSpeed:8.8,score:810})
 ],'选择'),
 level(14,'时间裂隙',[
  wave('裂隙侦察队',{count:8,formation:'stagger',drift:3.1,driftPattern:'pulse',firstDeployAfter:4.65,deployEvery:2.95,firstProjectileAfter:3.5,projectileEvery:2.85,score:620}),
  wave('裂隙投放队',{count:9,formation:'grid',drift:3.35,driftPattern:'pulse',deployPattern:'alternate',firstDeployAfter:3.65,deployEvery:2.55,firstProjectileAfter:2.8,projectileEvery:2.45,diveSpeed:8.75,powerDrops:[{afterDefeat:5,type:'slow',landing:'safe'}],score:730}),
  wave('裂隙突袭队',{count:9,formation:'wedge',health:3,drift:3.55,driftPattern:'pulse',deployPattern:'alternate',firstDeployAfter:2.9,deployEvery:2.3,firstProjectileAfter:2.4,projectileEvery:2.25,diveSpeed:8.95,score:850})
 ],'选择'),
 level(15,'火力检验',[
  wave('检验侦察队',{count:8,formation:'line',drift:3.15,firstDeployAfter:4.55,deployEvery:2.9,firstProjectileAfter:3.4,projectileEvery:2.75,powerDrops:[{afterDefeat:4,type:'double',landing:'gap'}],score:660}),
  wave('检验投放队',{count:9,formation:'stagger',health:3,drift:3.45,deployPattern:'alternate',firstDeployAfter:3.5,deployEvery:2.5,firstProjectileAfter:2.7,projectileEvery:2.35,diveSpeed:8.9,score:780}),
  wave('检验突袭队',{count:9,formation:'grid',health:3,drift:3.7,deployPattern:'alternate',firstDeployAfter:2.8,deployEvery:2.25,firstProjectileAfter:2.25,projectileEvery:2.15,diveSpeed:9.05,powerDrops:[{afterDefeat:5,type:'rapid',landing:'safe'}],score:910})
 ],'选择'),
 level(16,'边界压迫',[
  wave('边界巡航队',{count:9,formation:'wedge',drift:3.25,driftPattern:'sweep',firstDeployAfter:4.35,deployEvery:2.75,firstProjectileAfter:3.15,projectileEvery:2.6,score:700}),
  wave('边界投放队',{count:9,formation:'grid',health:3,drift:3.6,driftPattern:'sweep',deployPattern:'alternate',firstDeployAfter:3.35,deployEvery:2.4,firstProjectileAfter:2.5,projectileEvery:2.25,diveSpeed:9.0,score:820}),
  wave('边界突袭队',{count:10,formation:'stagger',health:3,drift:3.8,driftPattern:'sweep',deployPattern:'alternate',firstDeployAfter:2.65,deployEvery:2.15,firstProjectileAfter:2.1,projectileEvery:2.05,diveSpeed:9.15,score:960})
 ],'掌握'),
 level(17,'交错防线',[
  wave('防线侦察队',{count:9,formation:'stagger',drift:3.35,firstDeployAfter:4.2,deployEvery:2.65,firstProjectileAfter:3.0,projectileEvery:2.45,score:740}),
  wave('防线投放队',{count:10,formation:'wedge',health:3,drift:3.65,deployPattern:'alternate',firstDeployAfter:3.2,deployEvery:2.3,firstProjectileAfter:2.4,projectileEvery:2.15,diveSpeed:9.1,powerDrops:[{afterDefeat:5,type:'spread',landing:'gap'}],score:870}),
  wave('防线突袭队',{count:10,formation:'grid',health:3,drift:3.9,deployPattern:'alternate',firstDeployAfter:2.55,deployEvery:2.1,firstProjectileAfter:2.0,projectileEvery:1.95,diveSpeed:9.25,score:1010})
 ],'掌握'),
 level(18,'连环投放',[
  wave('连环巡航队',{count:10,formation:'grid',health:3,drift:3.45,firstDeployAfter:4.0,deployEvery:2.55,firstProjectileAfter:2.85,projectileEvery:2.3,score:780}),
  wave('连环投放队',{count:10,formation:'stagger',health:3,drift:3.75,deployPattern:'alternate',firstDeployAfter:3.05,deployEvery:2.2,firstProjectileAfter:2.25,projectileEvery:2.0,diveSpeed:9.2,score:910}),
  wave('连环突袭队',{count:10,formation:'wedge',health:3,drift:4.0,deployPattern:'alternate',firstDeployAfter:2.45,deployEvery:2.0,firstProjectileAfter:1.9,projectileEvery:1.85,diveSpeed:9.35,powerDrops:[{afterDefeat:6,type:'shield',landing:'safe'}],score:1050})
 ],'掌握'),
 level(19,'极限校准',[
  wave('校准侦察队',{count:10,formation:'line',health:3,drift:3.55,firstDeployAfter:3.9,deployEvery:2.45,firstProjectileAfter:2.7,projectileEvery:2.2,score:820}),
  wave('校准投放队',{count:10,formation:'grid',health:3,drift:3.85,deployPattern:'alternate',firstDeployAfter:2.95,deployEvery:2.15,firstProjectileAfter:2.15,projectileEvery:1.95,diveSpeed:9.3,powerDrops:[{afterDefeat:5,type:'rapid',landing:'gap'}],score:960}),
  wave('校准突袭队',{count:10,formation:'stagger',health:3,drift:4.1,deployPattern:'alternate',firstDeployAfter:2.35,deployEvery:1.95,firstProjectileAfter:1.8,projectileEvery:1.78,diveSpeed:9.45,powerDrops:[{afterDefeat:6,type:'slow',landing:'safe'}],score:1110})
 ],'掌握'),
 level(20,'铁翼终局',[
  wave('终局侦察队',{count:10,formation:'wedge',health:3,drift:3.7,driftPattern:'pulse',firstDeployAfter:3.8,deployEvery:2.35,firstProjectileAfter:2.55,projectileEvery:2.05,score:880}),
  wave('终局投放队',{count:10,formation:'grid',health:3,drift:4.0,driftPattern:'pulse',deployPattern:'alternate',firstDeployAfter:2.8,deployEvery:2.05,firstProjectileAfter:2.0,projectileEvery:1.85,diveSpeed:9.4,powerDrops:[{afterDefeat:5,type:'spread',landing:'gap'}],score:1030}),
  wave('终局突袭队',{count:10,formation:'stagger',health:3,drift:4.2,driftPattern:'pulse',deployPattern:'alternate',firstDeployAfter:2.2,deployEvery:1.85,firstProjectileAfter:1.65,projectileEvery:1.7,diveSpeed:9.6,powerDrops:[{afterDefeat:6,type:'shield',landing:'safe'}],score:1200})
 ],'掌握')
];
export const getLevel=id=>LEVELS.find(level=>level.id===id)||LEVELS[0];
