import * as THREE from '../vendor/three.module.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {buildModel} from '../model.js';import {buildTank} from '../tank/model.js';import {LEVEL_ONE,createLevelOne,reachable,move,endTurn} from './state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cellKey=p=>p.join(',');let state=createLevelOne(),selected='bird';
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf1e7');scene.fog=new THREE.Fog('#edf1e7',18,46);const host=$('#canvas'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;host.append(renderer.domElement);
const camera=new THREE.PerspectiveCamera(38,1,.1,100),controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=true;controls.target.set(0,0,0);camera.position.set(12,17,18);
scene.add(new THREE.HemisphereLight(0xfffef7,0x83947b,2.8));const sun=new THREE.DirectionalLight(0xfff0cc,2.4);sun.position.set(8,16,11);sun.castShadow=true;scene.add(sun);
const board=new THREE.Group(),units=new THREE.Group(),markers=new THREE.Group();scene.add(board,units,markers);const mats={ground:new THREE.MeshStandardMaterial({color:'#edf1e7',roughness:.85}),line:new THREE.MeshStandardMaterial({color:'#cbd4c4',roughness:.85}),rock:new THREE.MeshStandardMaterial({color:'#748172',roughness:.8}),goal:new THREE.MeshStandardMaterial({color:'#f2c531',emissive:'#765800',emissiveIntensity:.25}),threat:new THREE.MeshStandardMaterial({color:'#e99b80',transparent:true,opacity:.58}),move:new THREE.MeshStandardMaterial({color:'#f2c531',transparent:true,opacity:.55})};
const cells=[];function pos([x,y],height=0){return new THREE.Vector3((x-(LEVEL_ONE.cols-1)/2)*2,height,(y-(LEVEL_ONE.rows-1)/2)*2)}
for(let x=0;x<LEVEL_ONE.cols;x++)for(let y=0;y<LEVEL_ONE.rows;y++){const g=new THREE.Group();g.userData.cell=[x,y];g.position.copy(pos([x,y]));const tile=new THREE.Mesh(new THREE.BoxGeometry(1.88,.22,1.88),mats.ground);tile.receiveShadow=true;g.add(tile);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(tile.geometry),new THREE.LineBasicMaterial({color:'#cbd4c4'}));edge.position.y=.12;g.add(edge);board.add(g);cells.push(g)}
for(const p of LEVEL_ONE.threat){const danger=new THREE.Mesh(new THREE.PlaneGeometry(1.55,1.55),mats.threat);danger.rotation.x=-Math.PI/2;danger.position.copy(pos(p,.145));board.add(danger)}
for(const p of LEVEL_ONE.rocks){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(.68,0),mats.rock);r.position.copy(pos(p,.72));r.castShadow=true;board.add(r)}
function badge(p,label){const r=new THREE.Mesh(new THREE.CylinderGeometry(.62,.62,.04,24),mats.goal);r.rotation.x=Math.PI/2;r.position.copy(pos(p,.16));board.add(r);r.userData.label=label}badge(LEVEL_ONE.birdExit,'翼');badge(LEVEL_ONE.tankExit,'车');
const rig=buildModel();rig.poseCreature({stand:1,wing:.2,grounded:1});const bird=new THREE.Group();bird.add(rig.creature);const {tank}=buildTank();
function anchorToCell(group){const bounds=new THREE.Box3().setFromObject(group),center=bounds.getCenter(new THREE.Vector3());group.children.forEach(child=>{child.position.x-=center.x;child.position.z-=center.z;child.position.y-=bounds.min.y;});group.updateMatrixWorld(true);}
anchorToCell(bird);anchorToCell(tank);bird.scale.setScalar(.30);tank.scale.setScalar(.26);units.add(bird,tank);const rings={bird:ring('#e7b624'),tank:ring('#475641')};function ring(color){const r=new THREE.Mesh(new THREE.TorusGeometry(.72,.05,6,28),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9}));r.rotation.x=-Math.PI/2;units.add(r);return r}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let target={bird:null,tank:null};
function clearMarkers(){markers.clear()}function renderMarkers(){clearMarkers();if(state.status!=='playing'||state.acted[selected])return;for(const p of reachable(state,selected)){const m=new THREE.Mesh(new THREE.PlaneGeometry(1.56,1.56),mats.move);m.rotation.x=-Math.PI/2;m.position.copy(pos(p,.14));m.userData.cell=p;markers.add(m)}}
function sync(){for(const u of ['bird','tank']){const group=u==='bird'?bird:tank,to=pos(state[u],.19);if(!target[u])group.position.copy(to);else group.position.lerp(to,.18);(u==='bird'?rings.bird:rings.tank).position.copy(group.position);(u==='bird'?rings.bird:rings.tank).position.y=.16;(u==='bird'?rings.bird:rings.tank).visible=u===selected;}
 $('#stability').innerHTML=Array.from({length:8},(_,i)=>`<i style="opacity:${i<state.stability?1:.18}"></i>`).join('');$('#message').textContent=state.message;$$('.unit').forEach(b=>{const u=b.dataset.unit;b.classList.toggle('selected',u===selected);b.disabled=state.acted[u]||state.status!=='playing';});$('#end').disabled=state.status!=='playing';$('#end').style.opacity=state.status==='playing'?1:.45;renderMarkers();if(state.status!=='playing'){ $('#result-title').textContent=state.status==='won'?'遗迹入口已通过':'核心失稳';$('#result-copy').textContent=state.message;$('#result').showModal();}}
function choose(unit){if(state.status==='playing'&&!state.acted[unit]){selected=unit;sync()}}$$('.unit').forEach(b=>b.onclick=()=>choose(b.dataset.unit));
function attemptMove(p){if(state.status!=='playing')return;state=move(state,selected,p);sync()}function finish(){if(state.status!=='playing')return;state=endTurn(state);sync()}$('#end').onclick=finish;$('#restart').onclick=restart;$('#result-restart').onclick=restart;function restart(){$('#result').close();state=createLevelOne();selected='bird';target={bird:null,tank:null};sync()}
renderer.domElement.addEventListener('pointerup',e=>{if(e.target!==renderer.domElement)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(markers.children,true)[0];if(hit){let o=hit.object;while(o&&!o.userData.cell)o=o.parent;if(o)attemptMove(o.userData.cell)}});window.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();choose(selected==='bird'?'tank':'bird')}if(e.code==='Space'){e.preventDefault();finish()}});
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();sync();
function loop(){requestAnimationFrame(loop);if(state.status==='playing'){bird.rotation.y+=.002;rig.wings.forEach((w,i)=>w.rotation.x=Math.sin(performance.now()/230+i)*.12)}controls.update();renderer.render(scene,camera)}loop();
